### ISSUE TITLE
Provide a public API for uploading projects

### ISSUE THREAD

**Issue by PPPDUD** [GarboMuffin/placeholder#11]
^^ That would be really helpful.

**Comment by bubzilla** [comment]
adding a api could make it insanely easy to add project editing and ease of access by allowing you to publish projects to it from the editor

**Comment by ajskateboarder** [comment]
There seems to already be an API - `/api/projects/new`. You would need to make a POST request that contains the project and a title in the form body

**Comment by SurvExe1Pc** [comment]
> hell garbo could also make it so you can view the shared projects in the editor too

this is possible just annoying to do

**Comment by SurvExe1Pc** [comment]
the json is stored along with the assets ig you could monitor the requests then pack them into a zip then upload it to a temporary service then load the file and delete it off the server

**Comment by MasonYayYay** [comment]
> the json is stored along with the assets ig you could monitor the requests then pack them into a zip then upload it to a temporary service then load the file and delete it off the server

That sounds hard and annoying

**Comment by GarboMuffin** [comment]
Automated uploads are out of scope.

Editor integration would happen some other way, if ever
