### ISSUE TITLE
Storage Location (and some issues)

### ISSUE THREAD

**Issue by SurvExe1Pc** [GarboMuffin/placeholder#8]
Does this "placeholder" project have a public place where it stores projects, 
or at least if you have the url you can link to it to download the project?
 as if it did it would be useful with the url paramater: "project_url" to load projects 
that have custom extensions without needing a server of your own.

There is an problem with the assets not loading but using allorigins.win you can load a project from turbowarp-share
https://turbowarp.org/?project_url=https://api.allorigins.win/raw%3Furl%3Dhttps://share.turbowarp.org/api/projects/e57854f5-1f22-46f2-9fc3-47ee68e0e293

and yes I understand this is a placeholder and is subject to change or removal.

(edit):
added some stuff I already knew. and removed other edit

**Comment by GarboMuffin** [comment]
No, you can't use this with project_url

**Comment by SurvExe1Pc** [comment]
good to know.
