### ISSUE TITLE
VM? Turbo share

### ISSUE THREAD

**Issue by HeckerCatYT** [GarboMuffin/placeholder#9]
I tried sharing a project threw share turbowarp and it worked but when it loaded it said VM is too old for text animation. so i cant share my project with my friends without them downloading it which they dont want too.

**Comment by TONYflashB** [comment]
It works now. Although it doesn't work on the desktop app, it works everywhere else. Try it once again

**Comment by GarboMuffin** [comment]
It will work in the desktop app too if you download v1.8.0-beta.1. It's linked on the desktop app's website

**Comment by HeckerCatYT** [comment]
Ok! It works now.
